# -*- coding: utf-8 -*-
"""password generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZQFlDb5G4fOUQt69HXHY3aQJ_OAoGc3
"""

import random
import string

def generate_random_password(length):
  """Generates a random password of the specified length."""

  # Create a list of all possible characters in a password.
  characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")

  # Shuffle the list of characters to randomize the order.
  random.shuffle(characters)

  # Generate a random password by selecting characters from the list.
  password = "".join(random.choice(characters) for i in range(length))

  # Return the generated password.
  return password

# Generate a random password of length 10.
password = generate_random_password(10)

# Print the generated password.
print("Generated password:", password)