# -*- coding: utf-8 -*-
"""SIMPLE CALCULATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uaeu3u0p3ZlhGB96EZFzstwv6xEHif2L
"""

print("WELCOME TO SIMPLE CALCULATOR")
NUM1 = int(input("ENTER FIRST NUMBER:"))
NUM2 = int(input("ENTER SECOND NUMBER:"))
print("SELECT THE OPERATION YOU WANT TO PERFORM")
print("1.ADDITION")
print("2.SUBTRACTION")
print("3.MULTIPLICATION")
print("4.DIVISION ")
choice = int(input("ENTER THE OPERATION YOU WANT TO CARRY OUT"))
if choice == 1:
   print("YOUR ANSWER IS:", NUM1 + NUM2)
elif choice == 2:
   print("YOUR ANSWER IS:", NUM1 - NUM2)
elif choice == 3:
   print("YOUR ANSWER IS:", NUM1 * NUM2)
elif choice == 4:
   print("YOUR ANSWER IS:", NUM1 / NUM2)
else:
    print("INVALID INPUT")